language: ruby
rvm:
  - 1.9.3

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rake test_with_coveralls

before_script:
  - psql -c 'create database rubyclopedia_test' -U postgres