development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rubyclopedia_development
  pool: 5
  username: cbaldock
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rubyclopedia_test
  pool: 5
  username: cbaldock
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: rubyclopedia_production
  pool: 5
  username: cbaldock
  password: